name: Check Docs and Site Links

on:
  [push, pull_request]

jobs:
  check-links:
    name: Regularly check links
    runs-on: ubuntu-latest
    steps:
      # Stephen's fork of the Dark Linkchecker by filiph
      - name: Check docs links with linkcheck
        uses: StephenFluin/linkcheck-action@master
        with:
          arguments: https://docs.chain.link/
      - name: Check chain.link with linkcheck
        uses: StephenFluin/linkcheck-action@master
        with:
          arguments: https://chain.link
